apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres-volume-claim
  namespace: keycloak-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 250Mi
