apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-service
  namespace: keycloak-ns
spec:
  type: ClusterIP
  selector:
    app: keycloak-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
