apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-secret
  namespace: keycloak-ns
type: Opaque
stringData:
  POSTGRESQL_ROOT_KEY: postgres
  POSTGRESQL_ROOT_PASSWORD_KEY: postgres1
  POSTGRESQL_USER_KEY: keycloak
  POSTGRESQL_USER_PASSWORD_KEY: keycloak1
  POSTGRES_DB_KEY: keycloak
  POSTGRESQL_DB_URL_KEY: "jdbc:postgresql://keycloak-postgres-service/keycloak"
  POSTGRESQL_INIT_DB_KEY: |
    #!/bin/bash
    set -e

    echo "POSTGRES_USER: $POSTGRES_USER"
    echo "POSTGRES_PASSWORD: $POSTGRES_PASSWORD"
    echo ""
    echo "POSTGRES_APP_USER: $POSTGRES_APP_USER"
    echo "POSTGRES_APP_USER_PASSWORD: $POSTGRES_APP_USER_PASSWORD"
    echo "POSTGRES_APP_DB: $POSTGRES_APP_DB"

    psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER <<-EOSQL
    	CREATE USER $POSTGRES_APP_USER WITH ENCRYPTED PASSWORD '$POSTGRES_APP_USER_PASSWORD';
    	CREATE DATABASE "$POSTGRES_APP_DB";
    	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_APP_USER TO $POSTGRES_APP_DB;
        ALTER USER $POSTGRES_USER WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';
    EOSQL
